# Generated by Django 2.0 on 2017-12-15 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0003_auto_20171215_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.OneToOneField(default=1, on_delete=False, related_name='message_recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.OneToOneField(on_delete=False, related_name='message_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
